### ISSUE TITLE
Add a deprecated flag

### ISSUE THREAD

**Issue by mglax** [dpc/crev#105]
When reviewing a crate, it would be nice to be able to flag a crate as deprecated (a boolean in the review file most likely). When listing dependencies, deprecated crates should appear with its own custom format/color.

Example of output: 

    deprecated   1  1    17700     91937 0/2 crate_name               0.0.1

The rules for declaring a crate as deprecated should be strict and non opinionated (sometimes, people tend to judge as "deprecated" a bit too fast ;)). I think that only crates declared as deprecated by their own author should be treated as such.

**Comment by dpc** [comment]
I think you should just mark it as `rating: negative` and put `comment: deprecated`. I want to avoid creating too many states, fields and concepts, because while it helps one use-case, it complicates everything else.

**Comment by bwbroersma** [comment]
And then we can create a deprecation-bot we all trust to automatically give negative ratings & comments to deprecated crates. But if the bot makes an error, can we change/revoke a review, according to https://github.com/dpc/crev/issues/104 we should just update it by writing a new neutral review, however since neutral means "secure but with flaws" [crev-lib/rc/doc/editing-package-review.md](https://github.com/dpc/crev/blob/1f9c714d55b3da14f7721c3348e0e5ae82590f21/crev-lib/rc/doc/editing-package-review.md), neutral is not neutral, so either update the meaning of neutral or create a new status?
Also, since distrust propagates better than trust (a theory I remembered from reading some WoT papers), can we mark a user to trust just for distrust/negative reviews? :)

**Comment by dpc** [comment]
@bwbroersma That's a good comment.

Maybe I should just allow `null` (yaml `~` i believe) on `rating` to mean "no score".

**Comment by dpc** [comment]
Advisories are now implemented with `critical` field being a boolean. A non-critical advisory would pretty much mean that an upgrade is advised, for non-critical reasons.

**Comment by dpc** [comment]
I'm closing this one as done.
