### ISSUE TITLE
`cargo crev open <crate>`

### ISSUE THREAD

**Issue by dpc** [dpc/crev#139]
Similiar to `cargo crev goto`, but launching an user-defined command. The intention is to have user set and IDE, and get the crate opened for them for the review.

Good idea? Bad idea? 

I am trying to understand how to people want to review crate source code. eg. Vim users vs IDE users etc.

**Comment by kornelski** [comment]
On macOS `open <dir>` will show a directory using Finder. From there it's easy to browse files and open them in something else. That's likely a reasonable default for macOS.

Sublime Text can also nicely open a directory and that's what I would use to do a review. `$VISUAL` is close, but not quite, because the editor in `$VISUAL` has to wait for the edit to be done (which for a dir doesn't make sense). But if you offered that as a default option to edit, I could easily fix it (by deleting `-w` (wait)) arg.

**Comment by dpc** [comment]
Initial version (hardcoded) landed in 51c95c4fdbb5e2e01a4a542ada0a8be24dcda89f

**Comment by dpc** [comment]
You can now do `cargo crev open <crate> --cmd "code --wait -n" --cmd-save` etc. to use custom command (typically IDE) to open crates and remember that choice in the future.
