### ISSUE TITLE
Trust Proofs: Should there be one field, or two for trust.

### ISSUE THREAD

**Issue by dpc** [dpc/crev#4]
At least one user expressed that two are needed: https://www.reddit.com/r/rust/comments/99aiea/idea_for_a_scalable_code_reviewtrust_system_not/e4pc8rh/

So there could be eg.:

```
trust: some
transitive-trust: none
```

meaning "I trust code reviews of this person, but I don't necessarily trust people that this person trusts.

If we're going with two fields, things are becoming more complicated. How exactly should transitive trust work (especially that it is supposed to be configurable).

**Comment by Diggsey** [comment]
I think there should be three levels of trust you can give to an entity:
- I trust this entity to review code
- I trust the people this entity directly trusts to review code
- I trust the people this entity transitively trusts to review code

I was also thinking about how to represent different levels of trust without over-complicating things. I think a good way to do this would be via separate identities.

eg. let's say an organisation has three levels of trust for code, it could create "<Org>-Bronze", "<Org>-Silver", and "<Org>-Gold" identities, each with their own key pairs to manage that trust graph. This way you can reuse the same rules for creating the web of trust as for managing the relationships between trust level (ie. "Gold" => "Silver" => "Bronze")

This allows you to keep trust essentially binary, at least on an entity-by-entity basis, whilst still being really powerful.

You can also use this to manage different kinds of "distrust". eg. you could have an "<Org>-Security" identity, which distrusts crates with known security vulnerabilities, without implying that those crates are malicious in any way.

The command line tool should make it easy to manage multiple identities, so that a reviewer can review a crate with "different roles".

**Comment by dpc** [comment]
@Diggsey I don't really understand everything you've said.

Right now I'm of the opinion that both fields will be needed with `transitive-trust` by default (if not present) being of the same value as `trust` itself.

**Comment by dpc** [comment]
I'm not planing to add it right now, and it can always be introduced in backward-compat way.
