### ISSUE TITLE
Standardize on the hashing function

### ISSUE THREAD

**Issue by dpc** [dpc/crev#69]
So originally I was using [`Blake2b`](https://docs.rs/blake2/0.8.0/blake2/struct.Blake2b.html), but because it gives 512bit hashes, I thought they look too long, and we don't need more than 256bit. So I naively just trimmed the digest to first 32 bytes. Then I started thinking about it, and it looks like `Blake2b256` is something different than just first 32 bytes of `Blake2b(512)`. I'm not a cryptographer, so I am not even sure if taking 32B out of `Blake2b256` is secure. I think it is, but I have no 100% certainty.

I have a change ready to use [`VarBlake2b`](https://docs.rs/blake2/0.8.0/blake2/struct.VarBlake2b.html) to get the 32B output, but I'm not even sure if that's a "standard" `Blake2b-256` or what... I'm trying to figure it out in the issue: https://github.com/RustCrypto/hashes/issues/67

I could use some advise here, because ideally I'd like 256-bit standard blake2b function being used, so I am not inventing some weird stuff for no good reason.

**Comment by Ralith** [comment]
Blake2b's state is initialized with a [parameter block](https://tools.ietf.org/html/rfc7693#section-2.5) that includes, among other things, the configured output length. This should account for the difference from the fixed 512-byte version. My understanding is that, generally speaking, truncating hashes does not weaken them by more than the obvious reduction in entropy, but that it's desirable to make hashes used in different ways have uncorrelated output, hence the parameter block.

Blake2b by design supports arbitrary output lengths, so you shouldn't worry too much about using something weird. I have a project where I use 200-bit Blake2b hashes, because they divide neatly into both bytes and base32.

**Comment by dpc** [comment]
@Ralith Thanks. 

The point about encoding is a good one. I am using base64, and all my hashes end with `=` which is rather unfortunate.

**Comment by Ralith** [comment]
I use `VarBlake2b` because undermining mechanisms the authors put in place specifically to support htis sort of use-case seems imprudent.

> I am using base64, and all my hashes end with = which is rather unfortunate.

You almost certainly don't need to be using padded base64 regardless; that only exists to allow base64 streams to be concatenated, and can be omitted in all applications where the length of the base64 string is known. The only real downside to using a size that doesn't divide evenly into an encoding you'll be deploying widely is that the information density of encoded data will be very marginally reduced.

**Comment by dpc** [comment]
> You almost certainly don't need to be using padded base64 regardless

I have totally missed this. Thanks again!

**Comment by dpc** [comment]
All right. I've broken all formats of everything everywhere to be `VarBlake2b` with 256bit output, and base64 to be url safe, with no padding.

**Comment by dpc** [comment]
Hopefully for the last time.

**Comment by dpc** [comment]
It is done and released.
