### ISSUE TITLE
Effect of time on review proofs

### ISSUE THREAD

**Issue by Bert-Proesmans** [dpc/crev#70]
I read the doc pages and was left wondering how the system should be used __ over time __. People get smarter every day and a secure (neutral rating and above) library could become dangerous to use after a major bug is discovered. Given this context, I want to mention a few points.

- What should happen if a code reviewer finds out about a critical security vulnerability within a library that has a general status of secure? Is this a task for surrounding infrastructure, like automatically parsing published CSV items into a proof db? 
Also how would a distrust of all affected versions of a vulnerable library spread out ideally?

- Does the difference between review- and current time be accounted for in the final consideration of the security of a library?

- Is there value in creating a mass trust/distrust proof operation? Maybe an operation to distrust (retract) earlier trust proofs, belonging to the same user, according to a crate name filter would be useful?

**Comment by dpc** [comment]
I'll respond with my opinions, but I'm still open for suggestion and discussion. A lot of the answers here will probably be answered with time, by the users themselves. 

> What should happen if a code reviewer finds out about a critical security vulnerability within a library that has a general status of secure?

Create a new Package Review with `rating: dangerous` and publish it, possibly for many affected versions. Other people aware of it, should do the same.

>  Is this a task for surrounding infrastructure

I think so. Some users or projects might want to create an automated bot, with it's own Id, that monitors different sources and creates Package Reviews.

>  Also how would a distrust of all affected versions of a vulnerable library spread out ideally?

I was thinking, we might want to have something like "retweet" (take a review of another user, and create your own review based on it).

> Does the difference between review- and current time be accounted for in the final consideration of the security of a library?

Right now we record the time, and not do much about it, but it's entirely possible to use is more inteligently in the future. Right now if you write two reviews of the same crate and version, the newer one overwrites the previous ones. Same with Trust Proofs.

> Is there value in creating a mass trust/distrust proof operation? 

I was thinking about it myself.  Right now I'm of the opinion that it blows up the repositories, and creates too much noise, especially since we don't have good tooling around filtering important from less important (bulk) reviews.

**Comment by Bert-Proesmans** [comment]
Thanks for taking the time to reply. I agree with your opinions.

Incorporating the idea of trust proof depreciation as time goes by is probably a task too big and complex to handle. I do think however that this parameter shouldn't be ignored.
Certificates have a 'valid from' and 'valid until' range to prevent a public key to be trusted forever. I think this should be incorporated into trust proofs as well because a valid timespan is much easier to reason about than any hidden/implicit formula.
The variables are then reduced to 'how big is the timespan a proof should be trusted for, by default' (Considering this timespan will become user configurable to match release cycle plans).

**Comment by dpc** [comment]
My understanding is that  things like SSL certificates and GPG identities have a deadline to force their rotation and bound how long they can be abused in case they get stolen. I am not sure if we need an explicit deadline for Id's, especially that there is actually no such thing as ID Certificates.

Maybe `Crev` could just warn users, when detecting that a given Id was used for more than X years, that they should rotate it, and even start ignoring newer reviews issues by IDs that have been in use for too long. 

The problem here is ... there is no such thing as "issuance date" anywhere, and even there was it would be self-signed, so without any authoritative source.

Related issue: https://github.com/dpc/crev/issues/44

**Comment by Bert-Proesmans** [comment]
My comment was about the valid period of the trust proof itself. I intended at first to write a small sentence about not wanting to put too much focus on the certificate itself within the analogy, but couldn't get that clearly worded.

Your point is valid though. Since everybody self-signs it's possible to write down unrealistic start and end dates for the valid period.

I'll close this issue now because the more I think about it the more I realize I have absolutely no experience or answers to further develop this conversation. Thanks again for replying and your thoughts!
